name: Calculator UI automation

on:
  push:
    branches-ignore:
      - 'experiment/**'
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:
  
jobs:
  Execute-UI-Automation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          command: npm run test
      - name: Generate reports
        if: ${{ always() }}
        uses: cypress-io/github-action@v2
        with:
          command: npm run report
      - name: Upload screenshots
        uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - name: Upload mochawesome report
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: mochawesome-report
          path: mochawesome-report/ 